const letterContainer = document.getElementById('letter-container');
const optionsContainer = document.getElementById('options-container');  
const userInputSection = document.getElementById('user-input-section');
const newGameContainer = document.getElementById('new-game-container');
const newGameButton = document.getElementById('new-game-button');
const canvas = document.getElementById('canvas');
const resultText = document.getElementById('result-text');

// Options values for buttons
let options = {
    fruits: [
        'apple',
        'banana',
        'orange',
        'strawberry',
        'grapes',
        'mango',
        'watermelon',
        'pineapple',
        'kiwi',
        'pear',
        'peach',
        'plum',
        'cherry',
        'pomegranate',
        'lemon',
        'lime',
        'coconut',
        'blueberry',
        'raspberry',
        'blackberry',
        'apricot',
        'avocado',
        'fig',
        'grapefruit',
        'guava',
        'jackfruit',
        'lychee',
        'mandarin',
        'nectarine',
        'papaya',
        'passion fruit',
        'persimmon',
        'pumpkin',
        'tangerine',
        'tomato',
        'zucchini'
    ],
    animals: [
        'hedgehog',
        'rabbit',
        'cat',
        'dog',
        'mouse',
        'rat',
        'hamster',
        'gerbil',
        'guinea pig',
        'chinchilla',
        'squirrel',
        'chipmunk',
        'ferret',
        'weasel',
        'mink',
        'raccoon',
        'skunk',
        'badger',
        'otter',
        'beaver',
        'mole',
        'shrew',
        'bat',
        'pangolin',
        'anteater',
        'armadillo',
        'sloth',
        'aardvark',
        'elephant',
        'rhinoceros',
        'hippopotamus',
        'tapir',
        'horse',
        'zebra',
        'pig',
        'cow',
        'sheep',
        'goat',
        'deer',
        'giraffe',
        'camel',
        'llama',
        'alpaca',
        'moose',
        'elk',
        'reindeer',
        'caribou',
        'bison',
        'buffalo',
        'yak',
        'antelope',
        'gazelle',
        'lion',
        'tiger',
        'leopard',
        'cheetah',
        'jaguar',
        'cougar',
        'bobcat',
        'lynx',
        'panther',
        'puma',
        'hyena',
        'wolf',
        'fox',
        'coyote',
        'jackal',
        'bear',
        'polar bear',
        'panda bear',
        'koala',
        'kangaroo',
        'wallaby',
        'opossum',
        'wombat',
        'platypus',
        'echidna',
        'crocodile',
        'alligator',
        'turtle',
        'tortoise',
        'lizard',
        'snake',
        'iguana',
        'chameleon',
        'gecko',
        'frog',
        'toad',
        'salamander',
        'newt',
        'axolotl',
        'fish',
        'shark',
        'whale',
        'dolphin',
        'porpoise',
        'seal',
        'walrus',
    ],
    countries: [
        'America',
        'Argentina',
        'Brazil',
        'Canada',
        'Chile',
        'Colombia',
        'Cuba',
        'Ecuador',
        'Mexico',
        'Peru',
        'Venezuela',
        'Afghanistan',
        'Bahrain',
        'Bangladesh',
        'Bhutan',
        'Brunei',
        'Cambodia',
        'China',
        'Cyprus',
        'East Timor',
        'India',
        'Indonesia',
        'Iran',
        // ... Remaining country names
    ],
    Mythology: [
        'Achilles',
        'Aeneas',
        'Aphrodite',
        'Apollo',
        'Ares',
        'Artemis',
        'Athena',
        'Atlas',
        'Cronus',
        'Demeter',
        'Dionysus',
        'Hades',
        'Hecate',
        'Hephaestus',
        'Hera',
        'Hercules',
        'Hermes',
        'Hestia',
        'Medusa',
        'Odysseus',
        'Pan',
        'Persephone',
        'Poseidon',
        'Prometheus',
        'Zeus',
        // ... Remaining mythological names
    ],
    VideoGames: [
        'Mario',
        'Luigi',
        'Peach',
        'Bowser',
        'Yoshi',
        'Donkey Kong',
        'Link',
        'Zelda',
        'Ganondorf',
        'Samus',
        'Kirby',
        'Fox',
        'Pikachu',
        'Jigglypuff',
        'Captain Falcon',
        'Ness',
        'Marth',
        'Roy',
        'Ice Climbers',
        'Pit',
        'Wario',
        'Snake',
    ],
};

let winCount = 0;
let count = 0;

let chosenWord = '';

// display option buttons
const displayOptions = () => {
    optionsContainer.innerHTML += `<h3>Please Select An Option</h3>`;
    let buttonCon = document.createElement('div');
    for (let value in options) {
        buttonCon.innerHTML += `<button class='options' onclick='generateWord('${value}')'>${value}</button>`;
    }
    optionsContainer.appendChild(buttonCon);
};

// Block all the buttons
